# Travis config file
# ==================

language:
  python

python:
  - "3.6"

branches:
  only:
    - master
    - v0.6
    - v0.5

# Install test dependencies
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls

# Install project depencies
install:
  - pip install -r requirements.txt --quiet

# Run automated tests
script:
  - py.test

# Submit coverage report to coveralls
after_success:
    - if [[ $ENV == python=3.6* ]]; then
          coveralls;
      fi